########################################################################
#
# Makefile.config for compiling StormLib under linux
#  
#   set constants here (CFLAGS, LDFLAGS, the compiler to use, etc.)
#
# Author: Marko Friedemann <marko.friedemann@bmx-chemnitz.de>
# Created at: Mon Jan 29 18:26:01 CEST 2001
# Computer: whiplash.flachland-chemnitz.de 
# System: Linux 2.4.0 on i686
#    
# Copyright (c) 2001 BMX-Chemnitz.DE All rights reserved.
#
#####################################################################G++ = g++
#G++ = g++-3.0.1

CXXFLAGS = -Wall -g -I.
LDFLAGS = 

# installation flags: "-s" => strip; dont use together with CFLAG -g if you want to actually debug ;)
#I_FLAGS_ADD = -s
